### ISSUE TITLE
how to get the dataset used in `example.py`

### ISSUE THREAD

**Issue by homimickey** [saifkhichi96/versign-core#4]
Can i get the data set used in the `example.py` file please!!!!

`../../authentica/sources/db/datasets/Signatures/CustomDataset/'`
this folder structure like any zip file or a drive link as in like `models`

Amazing work bro !!

**Comment by saifkhichi96** [comment]
Please see my comment in #3 and let me know if that helps. Otherwise, I can try uploading the dataset I used on Kaggle.
